(function(){
'use strict';
var VERSION='14.6.5';
var K='sedori_settings_v1465';
var HK='sedori_market_history_v1465';
var CK='sedori_search_context_v1465';
var TIMEOUT=70000;
var timer=null;
var active=false;
var siteNames={mercari:'メルカリ',rakuma:'楽天ラクマ',yahoo_fleamarket:'Yahoo!フリマ',yahoo_auction:'Yahoo!オークション',jmty:'ジモティー'};
var fees={mercari:0.10,yahoo_fleamarket:0.05,rakuma:0.10,yahoo_auction:0.10,jmty:0};
function el(id){return document.getElementById(id)}
function num(v){var n=Number(v);return isFinite(n)?n:0}
function yen(v){return '¥'+Math.round(num(v)).toLocaleString('ja-JP')}
function pct(v){return (Math.round(num(v)*10)/10)+'%'}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function read(k,d){try{var x=localStorage.getItem(k);return x==null?d:JSON.parse(x)}catch(e){return d}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){return false}}
function status(t,err){var s=el('searchStatus');if(s){s.textContent=t;s.className='status'+(err?' error':'')}}
function setBoot(t,kind){var b=el('bootBanner');if(!b)return;b.textContent=t;b.className=kind==='err'?'errboot':kind==='ok'?'okboot':'';b.style.display='block'}
function bridgeVersion(){var d=document.documentElement&&document.documentElement.dataset?document.documentElement.dataset.sedoriUserscript:'';return d||''}
function updateBridge(){var v=bridgeVersion();var c=el('bridgeChip');if(c)c.textContent=v?'● Userscripts v'+v+' 接続済み':'● Userscripts 未接続';return !!v}
function filters(){return {query:(el('searchQ')?el('searchQ').value:'').trim(),min:num(el('searchMin')?el('searchMin').value:0),max:num(el('searchMax')?el('searchMax').value:0),condition:el('searchCondition')?el('searchCondition').value:'all',sort:el('searchSort')?el('searchSort').value:'newest',onSale:el('searchOnSale')?el('searchOnSale').checked:true,excludeAds:el('searchExcludeAds')?el('searchExcludeAds').checked:true,maxPerSite:50}}
function settings(){var d={minProfit:3000,minRoi:30,watchProfit:1500,watchRoi:15,saleSite:'mercari',shippingCost:750};var x=read(K,{});for(var k in x)d[k]=x[k];['minProfit','minRoi','watchProfit','watchRoi','shippingCost'].forEach(function(id){if(el(id)&&el(id).value!=='')d[id]=num(el(id).value)});if(el('saleSite'))d.saleSite=el('saleSite').value;return d}
function saveSettings(){write(K,settings());status('設定を保存しました。',false)}
function cmd(type,payload){var old=el('sedoriBridgeCommand');if(old&&old.parentNode)old.parentNode.removeChild(old);var n=document.createElement('div');n.id='sedoriBridgeCommand';n.hidden=true;var data={type:type,appVersion:VERSION,at:Date.now()};payload=payload||{};for(var k in payload)data[k]=payload[k];n.textContent=JSON.stringify(data);document.documentElement.appendChild(n)}
function normalize(s){return String(s||'').toLowerCase().replace(/[\s\-_/()【】\[\]・,，.。]+/g,' ').trim()}
function tokens(s){return normalize(s).split(' ').filter(function(x){return x.length>1})}
function score(a,b){var A=tokens(a),B=tokens(b);if(!A.length||!B.length)return 0;var hit=0;for(var i=0;i<A.length;i++){for(var j=0;j<B.length;j++){if(A[i]===B[j]||A[i].indexOf(B[j])>=0||B[j].indexOf(A[i])>=0){hit++;break}}}return Math.round(hit/Math.max(A.length,B.length)*100)}
function quantile(a,q){if(!a.length)return 0;var s=a.slice().sort(function(x,y){return x-y});var i=Math.round((s.length-1)*q);return s[Math.max(0,Math.min(s.length-1,i))]}
function history(){var cut=Date.now()-180*86400000;var a=read(HK,[]);return a.filter(function(x){return num(x.price)>0&&num(x.at)>=cut}).slice(0,4000)}
function saveHistory(items,q){var a=history();var map={};a.forEach(function(x){var id=x.url||x.source+'|'+normalize(x.title)+'|'+x.price;map[id]=x});items.forEach(function(x){if(num(x.price)<=0)return;var id=x.url||x.source+'|'+normalize(x.title)+'|'+x.price;map[id]={source:x.source,title:x.title,price:num(x.price),url:x.url||'',query:q,at:Date.now()}});var out=[];for(var k in map)out.push(map[k]);out.sort(function(a,b){return num(b.at)-num(a.at)});write(HK,out.slice(0,4000))}
function market(item,items,q){var p=[];items.forEach(function(x){if(x.url!==item.url&&num(x.price)>0&&score(item.title,x.title)>=55)p.push(num(x.price))});if(p.length<2){history().forEach(function(x){if(num(x.price)>0&&(score(item.title,x.title)>=60||score(q,x.title)>=60))p.push(num(x.price))})}if(!p.length)return {sell:0,low:0,high:0,count:0,confidence:0};var med=quantile(p,0.5);var band=p.filter(function(v){return v>=med*0.55&&v<=med*1.8});if(band.length>=3)p=band;var sell=Math.round(Math.min(quantile(p,0.35),quantile(p,0.5)*0.93)/100)*100;var conf=Math.min(92,45+p.length*6);if(p.length===1)conf=42;if(p.length===2)conf=58;return {sell:sell,low:Math.round(quantile(p,0.25)/100)*100,high:Math.round(quantile(p,0.75)/100)*100,count:p.length,confidence:conf}}
function shipping(item){var t=(item.title||'')+' '+(item.rawText||'');if(/リング|指輪|ネックレス|ピアス|ブレスレット|カード|小物/i.test(t))return 230;if(/財布|キーケース|スマホ|iphone|ゲームソフト|香水|化粧品/i.test(t))return 450;if(/バッグ|靴|スニーカー|ジャケット|コート|デニム|パンツ|ニット|パーカー|シャツ/i.test(t))return 750;if(/工具|家電|ホイール|タイヤ/i.test(t))return 1200;return 750}
function judge(item,items,q){var s=settings();var m=market(item,items,q);var buy=num(item.price);var fee=Math.round(m.sell*(fees[s.saleSite]==null?0.10:fees[s.saleSite]));var ship=shipping(item);var profit=m.sell?Math.round(m.sell-fee-ship-buy):0;var roi=buy?profit/buy*100:0;var verdict='pass',reason='利益不足';if(!m.sell){verdict='watch';reason='比較データ不足'}else if(m.confidence<48){verdict='watch';reason='低信頼'}else if(profit>=s.minProfit&&roi>=s.minRoi&&m.count>=2){verdict='buy';reason='仕入基準到達'}else if(profit>=s.watchProfit&&roi>=s.watchRoi){verdict='hold';reason='利益余地あり'}if(roi>300){verdict='watch';reason='異常ROIのため要確認'}return {source:item.source,title:item.title||'商品名不明',url:item.url||'',buy:buy,sell:m.sell,low:m.low,high:m.high,count:m.count,confidence:m.confidence,fee:fee,shipping:ship,profit:profit,roi:roi,verdict:verdict,reason:reason}}
function row(x){var label={buy:'仕入候補',hold:'保留',watch:'要確認',pass:'見送り'}[x.verdict]||'要確認';return '<div class="row" data-v="'+x.verdict+'"><div class="cell"><b>'+esc(x.title)+'</b><div class="muted">'+esc(x.reason)+'</div></div><div class="cell"><b>'+esc(siteNames[x.source]||x.source)+'</b></div><div class="cell">仕入 '+yen(x.buy)+'<br><span class="muted">手数料 '+yen(x.fee)+' / 送料 '+yen(x.shipping)+'</span></div><div class="cell">予測 '+(x.sell?yen(x.sell):'不可')+'<br><span class="muted">'+(x.low?yen(x.low)+'〜'+yen(x.high):'-')+' / '+x.count+'件 / 信頼'+x.confidence+'</span></div><div class="cell">利益 '+yen(x.profit)+'<br><span class="muted">ROI '+pct(x.roi)+'</span></div><div class="cell"><b class="badge '+x.verdict+'">'+label+'</b>'+(x.url?'<br><a href="'+esc(x.url)+'" target="_blank" rel="noopener">商品を見る</a>':'')+'</div></div>'}
function renderResult(data){data=data||{};var items=Array.isArray(data.items)?data.items:[];var q=(data.filters&&data.filters.query)||(read(CK,{query:''}).query)||'';var map={};items.forEach(function(x){var id=x.url||x.source+'|'+normalize(x.title)+'|'+x.price;if(!map[id])map[id]=x});items=[];for(var k in map)items.push(map[k]);saveHistory(items,q);var rows=items.map(function(x){return judge(x,items,q)});var order={buy:0,hold:1,watch:2,pass:3};rows.sort(function(a,b){return order[a.verdict]-order[b.verdict]||b.profit-a.profit});var c={buy:0,hold:0,watch:0,pass:0};rows.forEach(function(x){c[x.verdict]++});var sum=el('summary');if(sum){sum.innerHTML='<div class="sum"><small>検索完了</small><b>'+rows.length+'</b></div><div class="sum buy"><small>仕入候補</small><b>'+c.buy+'</b></div><div class="sum watch"><small>要確認</small><b>'+c.watch+'</b></div><div class="sum"><small>保留</small><b>'+c.hold+'</b></div><div class="sum pass"><small>見送り</small><b>'+c.pass+'</b></div><div class="sum"><small>予測価格あり</small><b>'+rows.filter(function(x){return x.sell>0}).length+'</b></div>';sum.classList.remove('hide')}
var out=el('candidateResults');if(out){out.innerHTML=rows.length?rows.map(row).join(''):'<div class="cell">結果なし</div>';out.classList.remove('hide')}
if(el('bulkSearchBtn'))el('bulkSearchBtn').disabled=false;active=false;clearTimeout(timer);status('検索完了：'+items.length+'件 / 予測 '+rows.filter(function(x){return x.sell>0}).length+'件 / 仕入候補 '+c.buy+'件',false)}
function consume(){updateBridge();var er=el('sedoriBridgeError');if(er){var em='不明';try{em=JSON.parse(er.textContent||'{}').message||em}catch(e){};if(er.parentNode)er.parentNode.removeChild(er);if(el('bulkSearchBtn'))el('bulkSearchBtn').disabled=false;active=false;status('検索エラー：'+em,true)}var r=el('sedoriBridgeResult');if(r){var d={};try{d=JSON.parse(r.textContent||'{}')}catch(e){};if(r.parentNode)r.parentNode.removeChild(r);renderResult(d)}}
function startSearch(){if(!updateBridge()){status('Userscriptsが未接続です。Safari拡張機能でUserscriptsをONにしてください。',true);return}var f=filters();if(!f.query){status('商品名・型番を入力してください。',true);return}write(CK,f);active=true;if(el('bulkSearchBtn'))el('bulkSearchBtn').disabled=true;status('5サイト検索を開始します…「'+f.query+'」',false);cmd('search',{filters:f});clearTimeout(timer);timer=setTimeout(function(){if(active){active=false;if(el('bulkSearchBtn'))el('bulkSearchBtn').disabled=false;status('70秒で待機解除しました。検索画面から戻っている場合はこの表示は無視してください。',true)}},TIMEOUT)}
function loginCheck(){if(!updateBridge()){status('Userscriptsが未接続です。',true);return}status('5サイトのログイン確認を開始します…',false);cmd('login',{})}
function tabs(){var bs=document.querySelectorAll('nav button[data-tab]');for(var i=0;i<bs.length;i++){bs[i].addEventListener('click',function(){var name=this.getAttribute('data-tab');var ids=['search','judge','history','settings'];for(var j=0;j<ids.length;j++){var p=el(ids[j]+'Panel');if(p)p.classList.toggle('hide',ids[j]!==name)}for(var k=0;k<bs.length;k++)bs[k].classList.remove('active');this.classList.add('active')})}}
function init(){try{window.__SEDORI_ENGINE__={version:VERSION};document.title='せどりAI v'+VERSION;if(el('releaseVersion'))el('releaseVersion').textContent='v'+VERSION;var ctx=read(CK,null);if(ctx&&ctx.query&&el('searchQ'))el('searchQ').value=ctx.query;var b=el('bulkSearchBtn');if(b)b.addEventListener('click',startSearch);if(el('searchQ'))el('searchQ').addEventListener('keydown',function(e){if(e.key==='Enter')startSearch()});if(el('saveSettingsBtn'))el('saveSettingsBtn').addEventListener('click',saveSettings);if(el('checkLoginBtn'))el('checkLoginBtn').addEventListener('click',loginCheck);tabs();if(typeof MutationObserver!=='undefined')new MutationObserver(consume).observe(document.documentElement,{childList:true,subtree:true});setInterval(consume,700);updateBridge();setBoot('✓ v14.6.5 判定エンジン起動完了','ok');status(updateBridge()?'準備完了。検索できます。':'Userscripts接続待ち。検索前にSafari拡張機能を確認してください。',false);setTimeout(function(){var bb=el('bootBanner');if(bb&&bb.className.indexOf('errboot')<0)bb.style.display='none'},2200)}catch(e){setBoot('起動エラー：'+String(e&&e.message?e.message:e),'err');status('起動エラー：'+String(e&&e.message?e.message:e),true)}}
window.addEventListener('error',function(e){setBoot('JavaScriptエラー：'+(e.message||'不明'),'err');status('JavaScriptエラー：'+(e.message||'不明'),true)});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();