const CFG={budget:50000,reserve:5000,radius:50,minProfit:3000,minMargin:20,buyScore:75,watchScore:55,risk:{low:0,medium:12,high:35}};
const $=id=>document.getElementById(id); const yen=n=>'¥'+Math.round(Number(n)||0).toLocaleString('ja-JP');
function feePct(source,payment){if(source==='mercari')return 10;if(source==='yahoo_fleamarket')return 5;if(source==='jmty')return payment==='cash'?0:5;return 10}
function analyze(x){let buy=+x.buy||0,sell=+x.sell||0,ship=+x.shipping||0,other=+x.other||0,feeP=feePct(x.source,x.payment),fee=Math.round(sell*feeP/100),profit=Math.round(sell-fee-ship-other-buy),margin=buy>0?profit/buy*100:-999;let score=50;score+=Math.min(Math.max((margin-10)*.8,-28),30);score+=Math.min(Math.max((profit-1000)/300,-15),20);score-=CFG.risk[x.auth]??12;score-=CFG.risk[x.cond]??12;if(+x.comps>=5)score+=5;else if(+x.comps===0)score-=12;if(x.source==='jmty'&&+x.distance>CFG.radius)score-=45;if(buy>CFG.budget-CFG.reserve)score-=60;score=Math.max(0,Math.min(100,Math.round(score*10)/10));let hp=[];if(buy<=0||sell<=0)hp.push('価格情報不足');if(buy>CFG.budget-CFG.reserve)hp.push('予算超過');if(x.auth==='high')hp.push('真贋リスク高');if(x.source==='jmty'&&+x.distance>CFG.radius)hp.push('50km圏外');let verdict=hp.length?'PASS':(profit>=CFG.minProfit&&margin>=CFG.minMargin&&score>=CFG.buyScore?'BUY':(score>=CFG.watchScore?'WATCH':'PASS'));return {...x,platform_fee_pct:feeP,platform_fee_yen:fee,expected_profit_yen:profit,margin_pct:Math.round(margin*10)/10,score,verdict,reason:hp.join(' / ')||'基準判定',saved_at:new Date().toISOString()}}
function formData(){return {source:$('source').value,category:$('category').value,title:$('title').value.trim(),url:$('url').value.trim(),buy:+$('buy').value,sell:+$('sell').value,shipping:+$('shipping').value,other:+$('other').value,auth:$('auth').value,cond:$('cond').value,comps:+$('comps').value,distance:+$('distance').value,payment:$('payment').value}}
let last=null;$('judgeBtn').onclick=()=>{last=analyze(formData());$('resultCard').style.display='block';$('verdict').textContent=last.verdict;$('verdict').className='verdict '+last.verdict.toLowerCase();$('profit').textContent=yen(last.expected_profit_yen);$('margin').textContent=last.margin_pct+'%';$('score').textContent=last.score;$('scoreFill').style.width=last.score+'%';$('reason').textContent='手数料 '+last.platform_fee_pct+'%｜'+last.reason;$('openItem').href=last.url||'#';$('openItem').style.opacity=last.url?'1':'.4';$('resultCard').scrollIntoView({behavior:'smooth',block:'center'})};
$('source').onchange=()=>{let j=$('source').value==='jmty';$('distanceWrap').classList.toggle('hide',!j);$('paymentWrap').classList.toggle('hide',!j)};
function getHistory(){try{return JSON.parse(localStorage.getItem('sedori_history')||'[]')}catch{return[]}} function setHistory(h){localStorage.setItem('sedori_history',JSON.stringify(h));renderHistory()}
$('saveBtn').onclick=()=>{if(!last)return;let h=getHistory();h.unshift({...last,id:crypto.randomUUID?crypto.randomUUID():String(Date.now())});setHistory(h);$('saveBtn').textContent='保存済み';setTimeout(()=>$('saveBtn').textContent='候補に保存',1200)};
function renderHistory(){let h=getHistory();$('historyCount').textContent=h.length+'件';$('history').innerHTML=h.length?'':'<p class="small">まだ候補はありません。</p>';h.forEach(x=>{let d=document.createElement('div');d.className='history-item';d.innerHTML=`<div class="history-head"><b>${escapeHtml(x.title||'名称未入力')}</b><span class="pill">${x.verdict}</span></div><div class="small">${yen(x.buy)} → ${yen(x.sell)}｜利益 ${yen(x.expected_profit_yen)}｜${x.margin_pct}%｜score ${x.score}</div>`;if(x.url){let a=document.createElement('a');a.href=x.url;a.target='_blank';a.rel='noopener';a.className='small';a.textContent='商品ページを開く';d.appendChild(a)}$('history').appendChild(d)})}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('clearBtn').onclick=()=>{if(confirm('保存した候補をすべて削除しますか？'))setHistory([])};
$('searchQ').oninput=()=>{let q=encodeURIComponent($('searchQ').value.trim());$('mercariLink').href='https://jp.mercari.com/search?keyword='+q;$('yahooLink').href='https://paypayfleamarket.yahoo.co.jp/search/'+q;$('jmtyLink').href='https://jmty.jp/all/sale?keyword='+q};$('searchQ').dispatchEvent(new Event('input'));
function csvEscape(v){let s=String(v??'');return /[",\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s}
$('exportBtn').onclick=()=>{let h=getHistory();if(!h.length)return alert('候補がありません');let cols=['saved_at','source','category','title','url','buy','sell','shipping','other','auth','cond','comps','distance','payment','platform_fee_pct','platform_fee_yen','expected_profit_yen','margin_pct','score','verdict','reason'];let csv='\uFEFF'+cols.join(',')+'\n'+h.map(r=>cols.map(c=>csvEscape(r[c])).join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='sedori_results.csv';a.click();URL.revokeObjectURL(a.href)};
$('importFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;let text=await f.text();let rows=parseCSV(text.replace(/^\uFEFF/,''));if(rows.length<2)return alert('CSVを読み込めませんでした');let cols=rows[0];let imported=rows.slice(1).filter(r=>r.some(v=>v.trim())).map(r=>Object.fromEntries(cols.map((c,i)=>[c,r[i]??'']))).map(o=>analyze({source:o.source||'mercari',category:o.category||'wallet',title:o.title||'',url:o.url||'',buy:+(o.buy||o.buy_price_yen||0),sell:+(o.sell||o.expected_sell_price_yen||0),shipping:+(o.shipping||o.shipping_yen||750),other:+(o.other||o.other_cost_yen||0),auth:o.auth||o.authenticity_risk||'medium',cond:o.cond||o.condition_risk||'medium',comps:+(o.comps||o.comps_count||3),distance:+(o.distance||o.distance_km||0),payment:o.payment||o.payment_method||'online'}));setHistory([...imported,...getHistory()]);e.target.value=''};
function parseCSV(t){let rows=[],row=[],cell='',q=false;for(let i=0;i<t.length;i++){let c=t[i];if(q){if(c==='"'&&t[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}}row.push(cell.replace(/\r$/,''));rows.push(row);return rows}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{['judgePanel','searchPanel','historyPanel'].forEach(id=>$(id).classList.toggle('hide',id!==b.dataset.tab));if(b.dataset.tab==='historyPanel')renderHistory();window.scrollTo({top:0,behavior:'smooth'})});
renderHistory(); if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
