(()=>{'use strict';
const VERSION='12.0.0';
const SITE_NAMES={mercari:'メルカリ',rakuma:'楽天ラクマ',yahoo_fleamarket:'Yahoo!フリマ',yahoo_auction:'Yahoo!オークション',jmty:'ジモティー'};
const SITE_IDS=Object.keys(SITE_NAMES);
const SELL_SITES=['yahoo_fleamarket','mercari','rakuma','yahoo_auction'];
const FEES={mercari:10,rakuma:10,yahoo_fleamarket:5,yahoo_auction:10,jmty:5};
const SHIPPING={tiny:230,small:450,medium:750,large:1000,xlarge:1600};
const LOGIN_URLS={mercari:'https://jp.mercari.com/',rakuma:'https://fril.jp/',yahoo_fleamarket:'https://paypayfleamarket.yahoo.co.jp/',yahoo_auction:'https://auctions.yahoo.co.jp/',jmty:'https://jmty.jp/users/sign_in'};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yen=n=>'¥'+Math.round(Number(n)||0).toLocaleString('ja-JP');
const pct=n=>(Math.round((Number(n)||0)*10)/10)+'%';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const norm=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[‐‑‒–—―]/g,'-').replace(/[^\p{L}\p{N}+.-]+/gu,' ').replace(/\s+/g,' ').trim();
const uniq=a=>[...new Set((a||[]).filter(Boolean))];
const median=a=>{const x=(a||[]).filter(Number.isFinite).slice().sort((p,q)=>p-q);if(!x.length)return 0;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const quantile=(a,q)=>{const x=(a||[]).filter(Number.isFinite).slice().sort((p,q)=>p-q);if(!x.length)return 0;const p=(x.length-1)*q,b=Math.floor(p),r=p-b;return x[b+1]===undefined?x[b]:x[b]+r*(x[b+1]-x[b])};
let LAST_ITEMS=[],LAST_RESULTS=[],lastManual=null;

function siteName(id){return SITE_NAMES[id]||id||'不明'}
function setHeader(){const p=document.querySelector('header p');if(p)p.textContent=`v${VERSION} 実用版｜純利益・最大仕入額・同一性・下振れ耐性で判定`;document.title=`せどりAI v${VERSION}`}
function status(t){if($('searchStatus'))$('searchStatus').textContent=t}
function searchFilters(){return{query:$('searchQ')?.value.trim()||'',min:+($('searchMin')?.value||0),max:+($('searchMax')?.value||0),condition:$('searchCondition')?.value||'all',sort:$('searchSort')?.value||'newest',onSale:$('searchOnSale')?.checked!==false,excludeAds:$('searchExcludeAds')?.checked!==false}}

function identity(text){
 const s=norm(text),tokens=s.split(' ').filter(Boolean);
 const brands=['cartier','カルティエ','tiffany','ティファニー','gucci','グッチ','hermes','エルメス','chanel','シャネル','louis vuitton','ルイヴィトン','nike','ナイキ','adidas','アディダス','apple','アップル','sony','ソニー','canon','キヤノン','nintendo','任天堂'];
 let brand=brands.find(b=>s.includes(norm(b)))||'';
 const models=[];
 const modelRe=/\b(?:iphone\s*\d{1,2}(?:\s*(?:pro\s*max|pro|plus|mini))?|pixel\s*\d{1,2}(?:a|\s*pro)?|galaxy\s*(?:s|a)\s*\d{1,2}(?:\s*(?:ultra|plus)|\+)?|[a-z]{1,5}[- ]?\d{2,8}[a-z0-9-]*)\b/gi;
 for(const m of s.matchAll(modelRe))models.push(norm(m[0]).replace(/\s+/g,''));
 const materials=[];for(const [k,re] of [['k18',/\bk18\b|18金/],['k14',/\bk14\b|14金/],['k10',/\bk10\b|10金/],['pt950',/\bpt950\b/],['pt900',/\bpt900\b/],['sv925',/\b(?:sv925|silver925)\b|シルバー925/],['stainless',/ステンレス|stainless/],['tungsten',/タングステン|tungsten/],['leather',/レザー|本革|leather/]])if(re.test(s))materials.push(k);
 const sizes=[];for(const m of s.matchAll(/(?:\b(\d{1,2})\s*号\b|\bsize\s*(\d{1,2})\b|\b(\d{1,2})\s*cm\b)/gi))sizes.push(m[1]||m[2]||m[3]);
 let category='other';if(/リング|指輪|ring/.test(s))category='ring';else if(/ネックレス|necklace/.test(s))category='necklace';else if(/ピアス|イヤリング|earring/.test(s))category='earring';else if(/時計|watch/.test(s))category='watch';else if(/財布|wallet/.test(s))category='wallet';else if(/バッグ|bag/.test(s))category='bag';else if(/iphone|pixel|galaxy|スマホ|スマートフォン/.test(s))category='phone';else if(/カメラ|camera/.test(s))category='camera';else if(/ゲーム|switch|playstation|xbox/.test(s))category='game';else if(/工具|tool|インパクト|ドリル/.test(s))category='tool';else if(/タイヤ|ホイール|車|バイク|自動車/.test(s))category='auto';
 const risk=[];if(/ジャンク|故障|動作未確認|不動|欠品|片方のみ|部品取り/.test(s))risk.push('故障・欠品リスク');if(/まとめ|セット|大量|詰め合わせ/.test(s))risk.push('セット商品');if(/互換|社外|ノーブランド|generic/.test(s))risk.push('互換・ノーブランド');
 const stop=new Set(['メンズ','レディース','中古','新品','美品','未使用','送料無料','リング','指輪','アクセサリー','商品','即決','即購入','送料込']);
 const terms=uniq(tokens.filter(t=>t.length>=2&&!stop.has(t)&&!/^\d+$/.test(t)).slice(0,16));
 return{brand:norm(brand),models:uniq(models),materials:uniq(materials),sizes:uniq(sizes),category,terms,risk};
}
function conflicts(a,b){if(a.category!=='other'&&b.category!=='other'&&a.category!==b.category)return 'カテゴリ不一致';if(a.brand&&b.brand&&a.brand!==b.brand)return 'ブランド不一致';if(a.models.length&&b.models.length&&!a.models.some(x=>b.models.includes(x)))return '型番不一致';if(a.materials.length&&b.materials.length&&!a.materials.some(x=>b.materials.includes(x)))return '素材不一致';if(a.sizes.length&&b.sizes.length&&!a.sizes.some(x=>b.sizes.includes(x)))return 'サイズ不一致';return ''}
function similarity(target,peer,query){const a=identity(target.title),b=identity(peer.title),q=identity(query);const bad=conflicts(q,b)||conflicts(a,b);if(bad)return{score:0,grade:'X',reason:bad};let score=.2,reasons=[];const cat=q.category!=='other'?q.category:a.category;if(cat!=='other'&&b.category===cat){score+=.25;reasons.push('カテゴリ')};const brand=q.brand||a.brand;if(brand&&b.brand===brand){score+=.22;reasons.push('ブランド')};const models=uniq([...q.models,...a.models]);if(models.length&&b.models.length&&models.some(x=>b.models.includes(x))){score+=.30;reasons.push('型番')};const mats=uniq([...q.materials,...a.materials]);if(mats.length&&b.materials.length&&mats.some(x=>b.materials.includes(x))){score+=.10;reasons.push('素材')};const sizes=uniq([...q.sizes,...a.sizes]);if(sizes.length&&b.sizes.length&&sizes.some(x=>b.sizes.includes(x))){score+=.06;reasons.push('サイズ')};const terms=uniq([...q.terms,...a.terms]),hits=terms.filter(t=>b.terms.includes(t)).length;if(terms.length){score+=.12*Math.min(1,hits/Math.max(2,Math.min(6,terms.length)));if(hits>=2)reasons.push('特徴語')};if(b.risk.length)score-=.12;score=clamp(score,0,1);const strict=!!(q.brand||q.models.length||q.materials.length||q.sizes.length);let grade='D';if(strict)grade=score>=.84?'A':score>=.68?'B':score>=.54?'C':'D';else grade=score>=.74?'B':score>=.60?'C':score>=.52?'D':'X';return{score,grade,reason:reasons.join('・')||'カテゴリ近似'}}
function cleanRows(rows){const seen=new Set(),out=[];for(const r of rows){const k=norm(r.x.title).slice(0,90)+'|'+Math.round(r.x.price/100)*100;if(!seen.has(k)){seen.add(k);out.push(r)}}if(out.length<4)return{rows:out,spread:spread(out.map(z=>z.x.price)),removed:rows.length-out.length};const p=out.map(z=>z.x.price),q1=quantile(p,.25),q3=quantile(p,.75),iqr=q3-q1,med=median(p),lo=Math.max(1,q1-1.5*iqr,med*.45),hi=Math.min(q3+1.5*iqr,med*2.2),f=out.filter(z=>z.x.price>=lo&&z.x.price<=hi);return{rows:f.length>=3?f:out,spread:spread((f.length>=3?f:out).map(z=>z.x.price)),removed:rows.length-(f.length>=3?f:out).length}}
function spread(p){const m=median(p);return p.length>1&&m?(quantile(p,.75)-quantile(p,.25))/m:0}
function shipping(category){if(['ring','necklace','earring','wallet'].includes(category))return SHIPPING.tiny;if(category==='watch')return SHIPPING.small;if(['phone','camera','game'].includes(category))return SHIPPING.medium;if(['bag','tool'].includes(category))return SHIPPING.large;if(category==='auto')return SHIPPING.xlarge;return SHIPPING.medium}
function money(buy,sell,fee,ship,other=0){const feeY=Math.round(sell*fee/100),profit=Math.round(sell-feeY-ship-other-buy),roi=buy>0?profit/buy*100:0,margin=sell>0?profit/sell*100:0;return{feeY,profit,roi,margin,net:sell-feeY-ship-other}}
function maxBuyFor(sell,fee,ship,targetProfit,targetRoi){if(!(sell>0))return 0;const net=sell-Math.round(sell*fee/100)-ship;const byProfit=net-targetProfit;const byRoi=net/(1+targetRoi/100);return Math.max(0,Math.floor(Math.min(byProfit,byRoi)/100)*100)}
function marketFor(item,all,query){const scored=[];for(const x of all){if(x===item||x.url===item.url||!(x.price>0))continue;const sim=similarity(item,x,query);if(sim.grade!=='X'&&sim.score>=.52)scored.push({x,sim})}scored.sort((a,b)=>b.sim.score-a.sim.score);const cleaned=cleanRows(scored.filter(z=>['A','B','C'].includes(z.sim.grade)));const rows=cleaned.rows,A=rows.filter(z=>z.sim.grade==='A').length,B=rows.filter(z=>z.sim.grade==='B').length,C=rows.filter(z=>z.sim.grade==='C').length,sources=new Set(rows.map(z=>z.x.source)).size;
 const strict=(()=>{const q=identity(query);return!!(q.brand||q.models.length||q.materials.length||q.sizes.length)})();
 const reliable=strict?(A>=2||(A>=1&&rows.length>=4&&sources>=2)):(rows.length>=5&&sources>=2&&cleaned.spread<=.9);
 const strong=strict?(A>=2&&rows.length>=3&&cleaned.spread<=.65):(rows.length>=8&&sources>=2&&cleaned.spread<=.55);
 const prices=rows.map(z=>z.x.price),base=reliable?quantile(prices,.35):0,safety=cleaned.spread>.75?.72:cleaned.spread>.5?.78:cleaned.spread>.3?.83:.88;
 const standard=base?Math.floor(base*safety/100)*100:0,low=prices.length?Math.floor(quantile(prices,.20)*Math.max(.62,safety-.08)/100)*100:0,high=prices.length?Math.floor(quantile(prices,.60)*Math.min(.94,safety+.05)/100)*100:0;
 let conf=Math.min(45,rows.length*6)+Math.min(20,sources*10)+Math.min(20,A*8+B*4);if(cleaned.spread>.75)conf-=18;else if(cleaned.spread>.5)conf-=10;if(!reliable)conf=Math.min(conf,44);if(strong)conf=Math.max(conf,68);conf=clamp(Math.round(conf),0,100);
 let best=null;for(const site of SELL_SITES){const sr=rows.filter(z=>z.x.source===site),sp=sr.map(z=>z.x.price);const est=sr.length>=2?Math.floor(quantile(sp,.35)*safety/100)*100:standard;if(!est)continue;const fee=FEES[site],ship=shipping(identity(item.title).category),m=money(item.price,est,fee,ship);const c={site,price:est,fee,ship,...m,sourceComps:sr.length};if(!best||c.profit>best.profit)best=c}if(!best){const site=SELL_SITES.includes(item.source)?item.source:'yahoo_fleamarket',fee=FEES[site],ship=shipping(identity(item.title).category);best={site,price:standard,fee,ship,...money(item.price,standard,fee,ship),sourceComps:0}}
 return{rows,A,B,C,sources,spread:cleaned.spread,removed:cleaned.removed,reliable,strong,confidence:conf,standard:best.price||standard,low,high,best,strict};
}
function judge(item,market){const id=identity((item.title||'')+' '+(item.rawText||'')),m=money(item.price,market.standard,market.best.fee,market.best.ship),low=money(item.price,market.low,market.best.fee,market.best.ship);const targetProfit=2000,targetRoi=25,watchProfit=800,watchRoi=12,maxBuy=maxBuyFor(market.standard,market.best.fee,market.best.ship,targetProfit,targetRoi);let verdict='PASS',reason=[];
 if(id.risk.length){verdict='PASS';reason.push(id.risk.join('・'))}
 else if(!market.reliable){verdict='HOLD';reason.push(`比較根拠不足（比較${market.rows.length}件・${market.sources}サイト）`)}
 else if(m.profit<=0){verdict='PASS';reason.push('安全売価では赤字')}
 else if(market.strong&&market.confidence>=65&&m.profit>=targetProfit&&m.roi>=targetRoi&&low.profit>0&&item.price<=maxBuy){verdict='BUY';reason.push('利益・ROI・比較根拠・下振れ耐性が基準到達')}
 else if(m.profit>=watchProfit&&m.roi>=watchRoi&&market.confidence>=45){verdict='WATCH';reason.push(item.price>maxBuy&&maxBuy>0?'利益はあるが仕入価格が上限超過':'利益はあるが確度または下振れ耐性が不足')}
 else{verdict='PASS';reason.push('利益またはROIが実用基準未達')}
 return{...item,market,...m,lowProfit:low.profit,maxBuy,verdict,reason:reason.join(' / ')};
}
function verdictLabel(v){return{BUY:'仕入候補',WATCH:'要確認',HOLD:'保留',PASS:'見送り'}[v]||v}
function confidenceLabel(n){return n>=80?'高':n>=65?'中':n>=45?'低':'不足'}
function renderSummary(results,total,siteCounts,excluded){const s=$('summary');if(!s)return;const count=v=>results.filter(x=>x.verdict===v).length,profit=results.filter(x=>x.verdict==='BUY').reduce((a,x)=>a+x.profit,0);s.innerHTML=`<div class="box"><span>取得</span><b>${total}</b></div><div class="box buy"><span>仕入候補</span><b>${count('BUY')}</b></div><div class="box watch"><span>要確認</span><b>${count('WATCH')}</b></div><div class="box hold"><span>保留</span><b>${count('HOLD')}</b></div><div class="box pass"><span>見送り</span><b>${count('PASS')}</b></div><div class="box buy"><span>仕入候補 利益合計</span><b>${yen(profit)}</b></div>`;s.classList.remove('hide');const counts=SITE_IDS.map(id=>`${siteName(id)} ${siteCounts[id]||0}件`).join('｜');status(`${total}件取得。${counts}。判定対象 ${results.length}件${excluded?`・検索条件不一致 ${excluded}件除外`:''}。最大仕入額は利益2,000円・ROI25%を両方満たす上限。`)}
function renderResults(items,siteCounts={}){LAST_ITEMS=items||[];const f=searchFilters(),accepted=[],excluded=[];for(const x of LAST_ITEMS){if(!x||!x.title||!(+x.price>0)||!x.url)continue;if(f.min&&x.price<f.min){excluded.push(x);continue}if(f.max&&x.price>f.max){excluded.push(x);continue}const qid=identity(f.query),iid=identity(x.title),bad=conflicts(qid,iid);if(bad){excluded.push(x);continue}accepted.push({...x,price:+x.price})}const results=accepted.map(x=>judge(x,marketFor(x,accepted,f.query)));results.sort((a,b)=>{const rank={BUY:4,WATCH:3,HOLD:2,PASS:1};return(rank[b.verdict]-rank[a.verdict])||(b.profit-a.profit)||(b.market.confidence-a.market.confidence)});LAST_RESULTS=results;renderSummary(results,LAST_ITEMS.length,siteCounts,excluded.length);const box=$('candidateResults');if(!box)return;box.innerHTML='';results.slice(0,40).forEach(x=>{const d=document.createElement('div');d.className='candidate';const img=document.createElement('img');img.src=x.image||'icons/icon-192.png';img.alt='';img.onerror=()=>{img.src='icons/icon-192.png'};const body=document.createElement('div');const spreadPct=Math.round(x.market.spread*100),peers=x.market.rows.slice(0,5).map(z=>`<div class="peer">${esc(siteName(z.x.source))}｜${yen(z.x.price)}｜${esc(z.sim.grade)} ${esc(z.x.title)}</div>`).join('');body.innerHTML=`<div class="source-line">検索元：${esc(siteName(x.source))}｜信頼度 ${x.market.confidence}/100（${confidenceLabel(x.market.confidence)}）</div><h3 class="candidate-title">${esc(x.title)}</h3><div class="moneyline">仕入 ${yen(x.price)} → 売却候補 ${esc(siteName(x.market.best.site))}｜安全売価 ${yen(x.market.standard)}</div><div class="profitline">純利益 <b>${yen(x.profit)}</b>｜ROI <b>${pct(x.roi)}</b>｜最大仕入額 <b>${yen(x.maxBuy)}</b></div><div class="candidate-data">相場：下限 ${yen(x.market.low)} / 基準 ${yen(x.market.standard)} / 上振れ ${yen(x.market.high)}<br>販売コスト：手数料 ${x.market.best.fee}%（${yen(x.feeY)}）＋送料 ${yen(x.market.best.ship)}<br>比較：A ${x.market.A}件 / B ${x.market.B}件 / C ${x.market.C}件｜${x.market.rows.length}件・${x.market.sources}サイト｜ばらつき ${spreadPct}%｜除外 ${x.market.removed}件<br><b>判定理由：</b>${esc(x.reason)}</div><div class="verdict ${x.verdict.toLowerCase()}">${verdictLabel(x.verdict)}</div><div class="candidate-actions"><a class="btn" href="${esc(x.url)}" target="_blank" rel="noopener">商品を見る</a><button class="btn primary js-detail">詳細判定へ</button></div>${peers?`<details><summary>比較根拠を見る</summary>${peers}</details>`:''}`;body.querySelector('.js-detail').onclick=()=>fillManual(x);d.append(img,body);box.appendChild(d)});box.classList.toggle('hide',!results.length);if(!results.length)status('条件に合う商品を判定できませんでした。検索語を具体化するか価格条件を広げてください。')}
function startBulkSearch(){const f=searchFilters();if(!f.query){status('商品名・型番を入力してください。');return}if($('candidateResults'))$('candidateResults').classList.add('hide');if($('summary'))$('summary').classList.add('hide');status('5サイトを同じ条件で検索中…');window.postMessage({type:'SEDORI_START_SEARCH',filters:f},location.origin);setTimeout(()=>{if(!window.__SEDORI_USERSCRIPT__&&(!$('candidateResults')||$('candidateResults').classList.contains('hide')))status('検索スクリプトを確認できません。Userscriptsを有効にして最新版を読み込んでください。')},3000)}
function fillManual(x){for(const [id,v] of Object.entries({source:x.source,sellChannel:x.market.best.site,feeRate:x.market.best.fee,title:x.title,url:x.url,buy:x.price,sell:x.market.standard,shipping:x.market.best.ship,other:0,auth:'medium',cond:'medium',comps:x.market.rows.length})){if($(id))$(id).value=v}showPanel('judgePanel');manualJudge()}
function manualJudge(){const buy=+($('buy')?.value||0),sell=+($('sell')?.value||0),fee=+($('feeRate')?.value||10),ship=+($('shipping')?.value||0),other=+($('other')?.value||0),comps=+($('comps')?.value||0),auth=$('auth')?.value||'medium',cond=$('cond')?.value||'medium',m=money(buy,sell,fee,ship,other),riskPenalty=(auth==='high'?25:auth==='medium'?8:0)+(cond==='high'?20:cond==='medium'?7:0),score=clamp(Math.round(50+Math.min(25,m.roi/2)+Math.min(20,m.profit/300)-riskPenalty+(comps>=5?8:comps>=2?3:-8)),0,100),maxBuy=maxBuyFor(sell,fee,ship+other,2000,25);let verdict=m.profit>=2000&&m.roi>=25&&score>=65&&buy<=maxBuy?'BUY':m.profit>=800&&m.roi>=12&&score>=45?'WATCH':'PASS';lastManual={buy,sell,fee,ship,other,comps,m,score,maxBuy,verdict,title:$('title')?.value||'',url:$('url')?.value||''};if($('resultCard'))$('resultCard').style.display='block';if($('verdict')){$('verdict').textContent=verdictLabel(verdict);$('verdict').className='result-verdict '+verdict.toLowerCase()}if($('profit'))$('profit').textContent=yen(m.profit);if($('margin'))$('margin').textContent=pct(m.roi);if($('maxBuy'))$('maxBuy').textContent=yen(maxBuy);if($('score'))$('score').textContent=score+'/100';if($('reason'))$('reason').textContent=`販売手数料 ${fee}%・送料等 ${yen(ship+other)}を差し引いた純利益で判定。仕入候補基準は純利益2,000円以上・ROI25%以上・評価65点以上。`;if($('openItem'))$('openItem').href=lastManual.url||'#'}
function showPanel(id){document.querySelectorAll('main>section').forEach(s=>s.classList.toggle('hide',s.id!==id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id))}
function renderLogin(statusMap={}){const box=$('loginResults');if(!box)return;box.innerHTML='';for(const id of SITE_IDS){const row=document.createElement('div');row.className='login-row';const st=statusMap[id],label=st==='in'?'ログイン済み':st==='out'?'要ログイン':'未確認';row.innerHTML=`<div><b>${siteName(id)}</b><div class="${st==='in'?'status-ok':st==='out'?'status-ng':''}">${label}</div></div><a class="btn" href="${LOGIN_URLS[id]}" target="_blank" rel="noopener">開く</a>`;box.appendChild(row)}}
function saveHistory(){if(!lastManual)return;let h=[];try{h=JSON.parse(localStorage.getItem('sedori_history_v12')||'[]')}catch{}h.unshift({...lastManual,savedAt:new Date().toISOString()});localStorage.setItem('sedori_history_v12',JSON.stringify(h.slice(0,100)));renderHistory()}
function renderHistory(){const box=$('history');if(!box)return;let h=[];try{h=JSON.parse(localStorage.getItem('sedori_history_v12')||'[]')}catch{}if($('historyCount'))$('historyCount').textContent=h.length+'件';box.innerHTML=h.length?'':'<p class="small">まだ候補はありません。</p>';for(const x of h){const d=document.createElement('div');d.className='history-item';d.innerHTML=`<div class="history-head"><b>${esc(x.title||'名称未入力')}</b><span class="pill">${verdictLabel(x.verdict)}</span></div><div class="small">${yen(x.buy)} → ${yen(x.sell)}｜利益 ${yen(x.m?.profit)}｜ROI ${pct(x.m?.roi)}｜最大仕入 ${yen(x.maxBuy)}</div>`;box.appendChild(d)}}
function selfTest(){try{const a=money(1000,3000,10,230),b=maxBuyFor(5000,10,230,2000,25),i=identity('K18 メンズ リング 18号');const ok=a.profit===1470&&b>0&&i.category==='ring'&&i.materials.includes('k18');return ok}catch{return false}}
function init(){setHeader();const ok=selfTest();status(ok?`v${VERSION} 自己診断合格。検索できます。`:`v${VERSION} 自己診断エラー。再読み込みしてください。`);if($('bulkSearchBtn'))$('bulkSearchBtn').onclick=startBulkSearch;if($('searchQ'))$('searchQ').addEventListener('keydown',e=>{if(e.key==='Enter')startBulkSearch()});if($('judgeBtn'))$('judgeBtn').onclick=manualJudge;if($('saveBtn'))$('saveBtn').onclick=saveHistory;if($('clearBtn'))$('clearBtn').onclick=()=>{if(confirm('保存候補をすべて削除しますか？')){localStorage.removeItem('sedori_history_v12');renderHistory()}};if($('checkLoginBtn'))$('checkLoginBtn').onclick=()=>{window.postMessage({type:'SEDORI_CHECK_LOGIN'},location.origin);renderLogin({})};document.querySelectorAll('nav button[data-tab]').forEach(b=>b.onclick=()=>showPanel(b.dataset.tab));window.addEventListener('message',e=>{if(e.source!==window)return;if(e.data?.type==='SEDORI_SEARCH_RESULTS')renderResults(Array.isArray(e.data.items)?e.data.items:[],e.data.siteCounts||{});if(e.data?.type==='SEDORI_LOGIN_STATUS')renderLogin(e.data.status||{})});renderLogin({});renderHistory()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
