(()=>{'use strict';
const VERSION='14.6.0',TIMEOUT=65000,K='sedori_settings_v1460',HK='sedori_market_history_v1460',CK='sedori_search_context_v1460',EK='sedori_enrich_v1460';
const S={mercari:'メルカリ',rakuma:'楽天ラクマ',yahoo_fleamarket:'Yahoo!フリマ',yahoo_auction:'Yahoo!オークション',jmty:'ジモティー'},F={mercari:.10,yahoo_fleamarket:.05,rakuma:.10,yahoo_auction:.10,jmty:0};
const $=id=>document.getElementById(id),yen=n=>'¥'+Math.round(+n||0).toLocaleString('ja-JP'),pct=n=>(Math.round((+n||0)*10)/10)+'%';let timer=0,seq=0,active=0,ctx=null;
const read=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
function settings(){const d={minProfit:3000,minRoi:30,watchProfit:1500,watchRoi:15,shippingMode:'auto',shippingCost:750,saleSite:'mercari',autoEnrich:true,...read(K,{})};for(const k of ['minProfit','minRoi','watchProfit','watchRoi','shippingCost'])if($(k)?.value!=='')d[k]=+$(k).value||d[k];if($('saleSite'))d.saleSite=$('saleSite').value;if($('shippingMode'))d.shippingMode=$('shippingMode').value;if($('autoEnrich'))d.autoEnrich=$('autoEnrich').checked!==false;return d}
function status(t,e=false){if($('searchStatus')){$('searchStatus').textContent=t;$('searchStatus').className='status'+(e?' error':'')}}
function connected(){const v=document.documentElement?.dataset?.sedoriUserscript||'';if($('bridgeChip'))$('bridgeChip').textContent=v?`● Userscripts v${v} 接続済み`:'● Userscripts 未接続';return!!v}
function filters(){return{query:$('searchQ')?.value.trim()||'',min:+($('searchMin')?.value||0),max:+($('searchMax')?.value||0),condition:$('searchCondition')?.value||'all',sort:$('searchSort')?.value||'newest',onSale:$('searchOnSale')?.checked!==false,excludeAds:$('searchExcludeAds')?.checked!==false,maxPerSite:50}}
function cmd(type,payload={}){document.getElementById('sedoriBridgeCommand')?.remove();const n=document.createElement('div');n.id='sedoriBridgeCommand';n.hidden=true;n.textContent=JSON.stringify({type,...payload,appVersion:VERSION,at:Date.now()});document.documentElement.appendChild(n)}
const norm=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim(),tok=s=>norm(s).split(/\s+/).filter(x=>x.length>1);
function identityScore(a,b){const A=tok(a),B=tok(b);if(!A.length||!B.length)return 0;const h=(X,Y)=>X.filter(x=>Y.some(y=>x===y||x.includes(y)||y.includes(x))).length/X.length;let z=Math.round((h(A,B)+h(B,A))/2*100);for(const r of [/iphone\s*\d+(?:\s*pro max|\s*pro|\s*plus)?/i,/switch\s*(?:oled|lite|有機el)?/i,/\bk(?:10|14|18|24)\b/i,/\bpt(?:850|900|950)\b/i,/\b\d{2,4}\s*gb\b/i,/\b\d{1,2}(?:\.5)?\s*号\b/i,/\btd\d{3}[a-z]?\b/i]){const x=String(a).match(r)?.[0]?.toLowerCase(),y=String(b).match(r)?.[0]?.toLowerCase();if(x&&y&&x!==y)z-=45}if(/ケースのみ|空箱|ジャンク|部品取り/i.test(a)!==/ケースのみ|空箱|ジャンク|部品取り/i.test(b))z-=25;return Math.max(0,Math.min(100,z))}
const auc=x=>x?.source==='yahoo_auction'||/オークション|入札|終了まで|1円スタート/i.test(x?.rawText||'');
function history(){const cut=Date.now()-180*864e5,m=new Map();for(const k of [HK,'sedori_market_history_v14515','sedori_market_history_v14514'])for(const x of read(k,[])){if(+x.price>0&&+x.at>=cut){const id=x.url||`${x.source}|${norm(x.title)}|${x.price}`,o=m.get(id);if(!o||+x.at>+o.at)m.set(id,x)}}return[...m.values()].sort((a,b)=>b.at-a.at).slice(0,5000)}
function saveHistory(a,q){const m=new Map(history().map(x=>[x.url||`${x.source}|${norm(x.title)}|${x.price}`,x])),now=Date.now();for(const x of a)if(!auc(x)&&+x.price>0)m.set(x.url||`${x.source}|${norm(x.title)}|${x.price}`,{title:x.title,price:+x.price,source:x.source,url:x.url||'',query:q,at:now});write(HK,[...m.values()].sort((a,b)=>b.at-a.at).slice(0,5000))}
const qtile=(a,q)=>{const s=[...a].sort((x,y)=>x-y);return s[Math.max(0,Math.min(s.length-1,Math.round((s.length-1)*q)))]||0};
function marketFrom(p,mode,base){let a=p.filter(x=>+x>0).map(Number).sort((x,y)=>x-y);if(!a.length)return{safe:0,low:0,high:0,count:0,confidence:0,mode:'none'};const med=qtile(a,.5),band=a.filter(x=>x>=med*.55&&x<=med*1.8);if(band.length>=3)a=band;const safe=Math.round(Math.min(qtile(a,.35),qtile(a,.5)*.93)/100)*100,spread=(a.at(-1)||1)/(a[0]||1),cap={exact:96,similar:88,history:84,query:80,hybrid:92}[mode]||44;let c=Math.min(cap,base+a.length*5);if(a.length===1)c=Math.min(c,48);if(a.length===2)c=Math.min(c,60);if(spread>3)c-=14;return{safe,low:Math.round(qtile(a,.25)/100)*100,high:Math.round(qtile(a,.75)/100)*100,count:a.length,confidence:Math.max(0,c),mode}}
function predict(x,items,q){const L=items.filter(y=>y.url!==x.url&&!auc(y)&&+y.price>0).map(y=>({p:+y.price,s:identityScore(x.title,y.title),q:identityScore(q,y.title)})),H=history().filter(y=>y.url!==x.url&&+y.price>0).map(y=>({p:+y.price,s:identityScore(x.title,y.title),q:identityScore(q,y.title)}));let p=L.filter(z=>z.s>=78).map(z=>z.p);if(p.length>=2)return marketFrom(p,'exact',66);p=L.filter(z=>z.s>=60).map(z=>z.p);if(p.length>=3)return marketFrom(p,'similar',60);p=H.filter(z=>z.s>=74).map(z=>z.p);if(p.length>=2)return marketFrom(p,'history',58);const l=L.filter(z=>z.s>=48).map(z=>z.p),h=H.filter(z=>z.s>=55||z.q>=55).map(z=>z.p);if(l.length>=2&&h.length)return marketFrom([...l,...h],'hybrid',58);if(identityScore(q,x.title)>=48){p=L.filter(z=>z.q>=48).map(z=>z.p);if(p.length>=3)return marketFrom(p,'query',54)}return{safe:0,low:0,high:0,count:0,confidence:0,mode:'none'}}
function shippingEstimate(x,s){if(s.shippingMode==='fixed')return{cost:+s.shippingCost||0,reason:'設定送料'};const t=`${x.title||''} ${x.rawText||''}`;if(/リング|指輪|ネックレス|ピアス|ブレスレット|カード|小物/i.test(t))return{cost:230,reason:'小型品'};if(/財布|キーケース|スマホ|iphone|ゲームソフト|香水|化粧品/i.test(t))return{cost:450,reason:'薄型品'};if(/バッグ|靴|スニーカー|ジャケット|コート|デニム|パンツ|ニット|パーカー|シャツ/i.test(t))return{cost:750,reason:'60〜80サイズ'};if(/工具|家電|ホイール|タイヤ/i.test(t))return{cost:1200,reason:'重量物'};return{cost:750,reason:'標準'}}
function economics(x,m,s){const buy=+x.price||0,sell=m.safe||0,sh=shippingEstimate(x,s),fee=Math.round(sell*(F[s.saleSite]??.10)),profit=sell?Math.round(sell-fee-sh.cost-buy):0;return{buy,sell,fee,shipping:sh.cost,shippingReason:sh.reason,profit,roi:buy?profit/buy*100:0,margin:sell?profit/sell*100:0}}
function auctionBuy(x,m){if(!auc(x))return+x.price||0;const b=+(String(x.rawText||'').match(/(?:入札|入札件数)\s*[:：]?\s*(\d+)/)?.[1]||0);return m.safe?Math.round(Math.max(+x.price||0,m.safe*(b>=8?.70:b>=3?.62:.55))/100)*100:(+x.price>1000?+x.price:0)}
function generateQuestions(x){const t=`${x.title||''} ${x.rawText||''}`,a=[];if(!/傷|汚れ|状態|使用感/i.test(t))a.push('目立つ傷・汚れ・使用感があれば、場所と程度を教えてください。');if(/リング|指輪/i.test(t)&&!/\d{1,2}(?:\.5)?\s*号/.test(t))a.push('リングサイズ（号数）を教えてください。');if(/バッグ|財布|ブランド/i.test(t)&&!/付属品|箱|保存袋|保証書/i.test(t))a.push('箱・保存袋・保証書など付属品の有無を教えてください。');if(/k18|pt900|pt950|金|プラチナ/i.test(t)&&!/刻印|重量|g\b/i.test(t))a.push('刻印内容と重量（g）を教えてください。');return(a.length?a:['説明にない不具合・欠品・強い使用感があれば教えてください。']).join('\n')}
function generateListing(x,r){const title=String(x.title||'').replace(/\s+/g,' ').trim().slice(0,70);return{title,description:`【商品】${title}\n【状態】${x.condition==='new'?'新品・未使用':x.condition==='used'?'使用感あり':'中古・良好'}\n【参考価格】${r.expectedSell?yen(r.expectedSell):'相場確認中'}\n【発送】丁寧に梱包し追跡可能な方法を基本に発送します。\n【注意】写真と説明をご確認のうえご購入ください。`}}
function judge(x,items,q){const s=settings(),m=predict(x,items,q),buy=auctionBuy(x,m),e=economics({...x,price:buy},m,s);let v='pass',code='THRESHOLD',r=[];if(!m.safe){v='watch';code='NO_MARKET';r.push('比較データ不足')}else if(m.confidence<48){v='watch';code='LOW_CONF';r.push('低信頼')}else if(e.profit>=s.minProfit&&e.roi>=s.minRoi&&m.count>=2&&m.confidence>=58){v='buy';code='BUY_OK';r.push('仕入基準到達')}else if(e.profit>=s.watchProfit&&e.roi>=s.watchRoi){v='hold';code='HOLD_OK';r.push('利益余地あり')}else if(e.profit<s.watchProfit){code='LOW_PROFIT';r.push('利益不足')}else{code='LOW_ROI';r.push('ROI不足')}if(auc(x)&&buy<=0){v='watch';code='AUCTION_UNKNOWN';r.push('落札見込不明')}if(e.roi>300){v='watch';code='ROI_OUTLIER';r.push('異常ROI抑止')}const l=generateListing(x,{expectedSell:m.safe});return{...x,buy,expectedSell:m.safe,marketLow:m.low,marketHigh:m.high,marketCount:m.count,confidence:m.confidence,marketMode:m.mode,fee:e.fee,shipping:e.shipping,shippingReason:e.shippingReason,profit:e.profit,roi:e.roi,margin:e.margin,verdict:v,reasonCode:code,reason:r.join(' / '),questionText:generateQuestions(x),listingTitle:l.title,listingDescription:l.description}}
const dedupe=a=>[...new Map((a||[]).map(x=>[x.url||`${x.source}|${norm(x.title)}|${x.price}`,x])).values()],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function row(x){const l={buy:'仕入候補',hold:'保留',watch:'要確認',pass:'見送り'}[x.verdict];return`<div class="row" data-v="${x.verdict}"><div class="cell"><b>${esc(x.title)}</b><div class="muted">${esc(x.reason)}</div><details><summary>質問・販売文</summary><div class="muted"><b>質問</b><br>${esc(x.questionText).replace(/\n/g,'<br>')}<br><br><b>販売文</b><br>${esc(x.listingDescription).replace(/\n/g,'<br>')}</div></details></div><div class="cell"><b>${S[x.source]||x.source}</b></div><div class="cell">仕入 ${yen(x.buy)}<br><span class="muted">手数料 ${yen(x.fee)} / 送料 ${yen(x.shipping)}</span></div><div class="cell">予測 ${x.expectedSell?yen(x.expectedSell):'不可'}<br><span class="muted">${x.marketLow?yen(x.marketLow)+'〜'+yen(x.marketHigh):'-'} / ${x.marketCount}件 / 信頼${x.confidence}</span></div><div class="cell">利益 ${yen(x.profit)}<br><span class="muted">ROI ${pct(x.roi)}</span></div><div class="cell"><b class="badge ${x.verdict}">${l}</b>${x.url?`<br><a href="${esc(x.url)}" target="_blank">商品を見る</a>`:''}</div></div>`}
function extraUI(){if(!$('diagnostics')&&$('summary')){const d=document.createElement('div');d.id='diagnostics';d.className='panel hide';$('summary').after(d)}if(!$('profitSettings')&&$('settingsPanel')){const p=document.createElement('div');p.id='profitSettings';p.className='panel';p.innerHTML='<h3>利益計算</h3><label>販売先</label><select id="saleSite"><option value="mercari">メルカリ10%</option><option value="yahoo_fleamarket">Yahoo!フリマ5%</option><option value="rakuma">楽天ラクマ10%安全側</option><option value="yahoo_auction">Yahoo!オークション10%安全側</option><option value="jmty">ジモティー0%</option></select><label>送料</label><select id="shippingMode"><option value="auto">自動推定</option><option value="fixed">固定</option></select><input id="shippingCost" type="number" value="750"><label><input id="autoEnrich" type="checkbox" checked style="width:auto"> データ不足時に自動追加収集</label>';$('settingsPanel').appendChild(p)}}
function broaderQuery(q){const stop=new Set(['新品','未使用','美品','中古','メンズ','レディース','正規品','本物']);return tok(q).filter(x=>!stop.has(x)&&!/^\d{1,2}(?:\.5)?号$/.test(x)).slice(0,4).join(' ')}
function start(f=filters(),enrich=false){if(!connected())return status('Userscriptsが未接続です。',true);if(!f.query)return status('商品名・型番を入力してください。',true);ctx=f;write(CK,f);active=++seq;$('bulkSearchBtn').disabled=true;status(enrich?'データ不足のため追加収集中…':`5サイト検索中…「${f.query}」`);cmd('search',{filters:f,searchSeq:active,enrich});clearTimeout(timer);timer=setTimeout(()=>{$('bulkSearchBtn').disabled=false;active=0;status('65秒で検索待機を解除しました。',true)},TIMEOUT)}
function render(x){let items=dedupe(x.items||[]),q=x.filters?.query||ctx?.query||'';const en=read(EK,null);if(en?.active){items=dedupe([...(en.items||[]),...items]);q=en.q;write(EK,null)}saveHistory(items,q);const rows=items.map(i=>judge(i,items,q)).sort((a,b)=>(({buy:0,hold:1,watch:2,pass:3}[a.verdict]-{buy:0,hold:1,watch:2,pass:3}[b.verdict])||b.profit-a.profit));const c={buy:0,hold:0,watch:0,pass:0};rows.forEach(r=>c[r.verdict]++);$('summary').innerHTML=`<div class="sum"><small>検索完了</small><b>${rows.length}</b></div><div class="sum buy"><small>仕入候補</small><b>${c.buy}</b></div><div class="sum watch"><small>要確認</small><b>${c.watch}</b></div><div class="sum"><small>保留</small><b>${c.hold}</b></div><div class="sum pass"><small>見送り</small><b>${c.pass}</b></div><div class="sum"><small>予測価格あり</small><b>${rows.filter(r=>r.expectedSell).length}</b></div>`;$('summary').classList.remove('hide');$('candidateResults').innerHTML=rows.map(row).join('')||'<div class="cell">結果なし</div>';$('candidateResults').classList.remove('hide');$('bulkSearchBtn').disabled=false;status(`検索完了：${items.length}件 / 予測 ${rows.filter(r=>r.expectedSell).length}件 / 仕入候補 ${c.buy}件`);if(!en?.active&&settings().autoEnrich&&items.length&&rows.filter(r=>r.expectedSell).length<Math.min(5,Math.ceil(items.length*.25))){const b=broaderQuery(q);if(b&&norm(b)!==norm(q)){write(EK,{active:true,items,q});setTimeout(()=>start({...filters(),query:b},true),300)}}}
function consume(){connected();const e=$('sedoriBridgeError');if(e){let x={};try{x=JSON.parse(e.textContent||'{}')}catch{}status('検索エラー：'+(x.message||'不明'),true);e.remove();$('bulkSearchBtn').disabled=false}const r=$('sedoriBridgeResult');if(r){let x={};try{x=JSON.parse(r.textContent||'{}')}catch{}r.remove();if(x.searchSeq&&active&&+x.searchSeq!==active)return;render(x);active=0}}
function init(){extraUI();document.title=`せどりAI v${VERSION}`;const h=document.querySelector?.('.brand h1 small');if(h)h.textContent=`v${VERSION}`;ctx=read(CK,null);if(ctx?.query&&$('searchQ'))$('searchQ').value=ctx.query;connected();$('bulkSearchBtn')?.addEventListener('click',()=>start());$('searchQ')?.addEventListener('keydown',e=>e.key==='Enter'&&start());$('saveSettingsBtn')?.addEventListener('click',()=>{write(K,settings());status('設定を保存しました。')});$('checkLoginBtn')?.addEventListener('click',()=>connected()&&cmd('loginCheck'));if(typeof MutationObserver!=='undefined')new MutationObserver(consume).observe(document.documentElement,{childList:true,subtree:true});setInterval(consume,1000);status(connected()?'準備完了。検索できます。':'Userscripts接続待ち…')}
window.__SEDORI_ENGINE__={version:VERSION,identityScore,marketFrom,predict,shippingEstimate,economics,generateQuestions,generateListing,judge,broaderQuery};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
