(()=>{'use strict';
const VERSION='8.2.5';
const $=id=>document.getElementById(id);
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const yen=n=>'¥'+Math.round(Number(n)||0).toLocaleString('ja-JP');
const pct=n=>(Math.round((Number(n)||0)*10)/10)+'%';
const SITE_NAMES={mercari:'メルカリ',rakuma:'楽天ラクマ',yahoo_fleamarket:'Yahoo!フリマ',yahoo_auction:'Yahoo!オークション',jmty:'ジモティー'};
const DEFAULTS={minProfit:3000,minRoi:30,watchProfit:1500,watchRoi:15,fees:{mercari:10,rakuma:10,yahoo_fleamarket:5,yahoo_auction:10,jmty:5}};
function loadSettings(){try{const x=JSON.parse(localStorage.getItem('sedori_settings_v8')||'null')||{};return{...DEFAULTS,...x,fees:{...DEFAULTS.fees,...(x.fees||{})}}}catch{return JSON.parse(JSON.stringify(DEFAULTS))}}
function showTab(id){['searchPanel','judgePanel','historyPanel','settingsPanel'].forEach(x=>$(x)?.classList.toggle('hide',x!==id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));}
function syncConditional(){const source=$('source')?.value,sell=$('sellChannel')?.value;$('distanceWrap')?.classList.toggle('hide',source!=='jmty');$('paymentWrap')?.classList.toggle('hide',sell!=='jmty');}
function updateFee(){const s=loadSettings(),site=$('sellChannel')?.value||'yahoo_fleamarket',cash=site==='jmty'&&$('payment')?.value==='cash';if($('feeRate'))$('feeRate').value=cash?0:Number(s.fees[site]??10);syncConditional();}
function moneyMath({buy,sell,fee,ship,other},settings){const feeY=Math.round(sell*fee/100),net=sell-feeY-ship-other,profit=Math.round(net-buy),roi=buy>0?profit/buy*100:0,maxByProfit=Math.floor(net-settings.minProfit),maxByRoi=settings.minRoi>0?Math.floor(net/(1+settings.minRoi/100)):Math.floor(net),maxBuy=Math.max(0,Math.min(maxByProfit,maxByRoi));return{feeY,net,profit,roi,maxBuy}}
function verdictLabel(v){return({BUY:'仕入候補',WATCH:'要確認',HOLD:'保留',PASS:'見送り'})[v]||'不明'}
function analyze(){const settings=loadSettings(),buy=+$('buy')?.value||0,sell=+$('sell')?.value||0,fee=+$('feeRate')?.value||0,ship=+$('shipping')?.value||0,other=+$('other')?.value||0,comps=+$('comps')?.value||0,auth=$('auth')?.value||'medium',cond=$('cond')?.value||'medium',m=moneyMath({buy,sell,fee,ship,other},settings);let score=45+clamp(m.profit/Math.max(1,settings.minProfit)*22,-20,28)+clamp(m.roi/Math.max(1,settings.minRoi)*18,-15,24)+Math.min(12,comps*2);if(auth==='high')score-=25;else if(auth==='medium')score-=8;if(cond==='high')score-=18;else if(cond==='medium')score-=6;score=clamp(Math.round(score),0,100);let verdict='PASS',reason=[];if(!buy||!sell){verdict='HOLD';reason.push('仕入価格または想定売価が不足');}else if(comps<2){verdict='HOLD';reason.push('相場比較が2件未満');}else if(m.profit<=0){verdict='PASS';reason.push('想定売価では赤字');}else if(m.profit>=settings.minProfit&&m.roi>=settings.minRoi&&score>=70&&auth!=='high'&&cond!=='high'){verdict='BUY';reason.push('利益・投資利益率・リスクが仕入候補基準に到達');}else if(m.profit>=settings.watchProfit&&m.roi>=settings.watchRoi&&score>=50){verdict='WATCH';reason.push('利益候補だが仕入候補の安全条件には未到達');}else{verdict='PASS';reason.push('利益または投資利益率が基準未達');}if(auth==='high')reason.push('真贋リスクが高い');if(cond==='high')reason.push('状態リスクが高い');return{source:$('source')?.value||'mercari',sell_channel:$('sellChannel')?.value||'yahoo_fleamarket',fee_rate:fee,category:$('category')?.value||'other',title:$('title')?.value?.trim()||'',url:$('url')?.value?.trim()||'',buy,sell,shipping:ship,other,auth,cond,comps,expected_profit_yen:m.profit,margin_pct:Math.round(m.roi*10)/10,max_buy:m.maxBuy,score,verdict,reason:reason.join(' ／ '),saved_at:new Date().toISOString()}}
function questions(x){if(x.verdict==='PASS')return'';const q=[];if(['wallet','accessory','precious_metals'].includes(x.category))q.push('刻印・ロゴ・シリアルなど識別に必要な箇所の写真を追加いただけますか？','サイズ・重量・素材・付属品を分かる範囲で教えてください。');else if(x.category==='electronics')q.push('型番・シリアルが分かる写真を追加いただけますか？','動作確認済みの機能と不具合の有無を教えてください。');else if(x.category==='tool')q.push('正確な型番と本体ラベルの写真を追加いただけますか？','動作・異音・軸ブレ・バッテリー状態を教えてください。');else if(x.category==='auto')q.push('型番・サイズ・適合情報が分かる刻印やラベルの写真をお願いします。','傷・歪み・修理歴・欠品の有無を教えてください。');else q.push('型番・サイズ・付属品・目立つ傷や不具合を教えてください。');if(x.auth!=='low')q.push('真贋確認に必要なロゴ・刻印・タグなどの追加写真をお願いできますか？');return`購入を検討しています。お手数ですが、以下をご確認ください。\n\n${q.map((v,i)=>`${i+1}. ${v}`).join('\n')}\n\nよろしくお願いいたします。`}
function render(){const x=analyze();x.seller_questions=questions(x);window.__SEDORI_LAST_MANUAL__=x;const card=$('resultCard');if(card)card.style.display='block';if($('verdict')){$('verdict').textContent=verdictLabel(x.verdict);$('verdict').className='result-verdict '+x.verdict.toLowerCase()}if($('profit'))$('profit').textContent=yen(x.expected_profit_yen);if($('margin'))$('margin').textContent=pct(x.margin_pct);if($('maxBuy'))$('maxBuy').textContent=yen(x.max_buy);if($('score'))$('score').textContent=x.score+'点';if($('reason'))$('reason').textContent=x.reason;if($('openItem')){$('openItem').href=x.url||'#';$('openItem').style.opacity=x.url?'1':'.45'}if($('questionBox'))$('questionBox').classList.toggle('hide',!x.seller_questions);if($('questionText'))$('questionText').value=x.seller_questions||'';card?.scrollIntoView({behavior:'smooth',block:'center'});}
function saveLast(){const x=window.__SEDORI_LAST_MANUAL__;if(!x)return;let h=[];try{h=JSON.parse(localStorage.getItem('sedori_history')||'[]')}catch{};const id=crypto?.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());h.unshift({...x,id});localStorage.setItem('sedori_history',JSON.stringify(h));const b=$('saveBtn');if(b){b.textContent='保存済み';setTimeout(()=>b.textContent='候補に保存',1200)}}
function bind(){document.querySelectorAll('nav button[data-tab]').forEach(b=>{if(b.dataset.fallback825)return;b.dataset.fallback825='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();showTab(b.dataset.tab)},true)});const j=$('judgeBtn');if(j&&!j.dataset.fallback825){j.dataset.fallback825='1';j.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();try{render()}catch(err){console.error(err);const card=$('resultCard');if(card)card.style.display='block';if($('verdict'))$('verdict').textContent='判定エラー';if($('reason'))$('reason').textContent='判定処理でエラーが発生しました。画面を再読み込みしてください。'}},true)}const s=$('saveBtn');if(s&&!s.dataset.fallback825){s.dataset.fallback825='1';s.addEventListener('click',e=>{if(!window.__SEDORI_LAST_MANUAL__)return;e.preventDefault();e.stopImmediatePropagation();saveLast()},true)}const c=$('copyQuestionBtn');if(c&&!c.dataset.fallback825){c.dataset.fallback825='1';c.addEventListener('click',async e=>{const t=$('questionText')?.value;if(!t)return;e.preventDefault();e.stopImmediatePropagation();await navigator.clipboard.writeText(t);c.textContent='コピー済み';setTimeout(()=>c.textContent='質問文をコピー',1200)},true)}$('source')?.addEventListener('change',syncConditional);$('sellChannel')?.addEventListener('change',updateFee);$('payment')?.addEventListener('change',updateFee);syncConditional();window.__SEDORI_MANUAL_UI_VERSION__=VERSION;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();