'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const elements=new Map();
function el(id){if(!elements.has(id))elements.set(id,{id,value:'',textContent:'',innerHTML:'',style:{},disabled:false,checked:true,className:'',href:'',classList:{add(){},remove(){},toggle(){},contains(){return false}},addEventListener(){},appendChild(){},append(){},querySelector(){return null},focus(){}});return elements.get(id)}
const document={readyState:'complete',getElementById:id=>el(id),querySelector(sel){if(sel==='header p')return el('headerp');return null},querySelectorAll(){return[]},addEventListener(){},createElement(tag){return{tagName:tag.toUpperCase(),className:'',innerHTML:'',textContent:'',style:{},href:'',download:'',dataset:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},appendChild(){},append(){},querySelector(){return{onclick:null}},click(){}}}};
const store=new Map();
const windowObj={document,location:{origin:'https://example.test',href:'https://example.test/'},addEventListener(){},postMessage(){},__SEDORI_USERSCRIPT__:true};windowObj.window=windowObj;
const context={window:windowObj,document,localStorage:{getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},navigator:{clipboard:{writeText:async()=>{}}},location:windowObj.location,console,setTimeout,clearTimeout,setInterval,clearInterval,confirm:()=>true,Blob:function(){},URL:{createObjectURL(){return'blob:x'},revokeObjectURL(){}},Date,Math,Number,String,Object,Array,Set,Map,JSON,RegExp};
vm.createContext(context);vm.runInContext(fs.readFileSync('./app.js','utf8'),context,{filename:'app.js'});
const E=windowObj.__SEDORI_ENGINE__;assert(E,'engine not exposed');assert.strictEqual(E.version,'13.0.0');assert.strictEqual(windowObj.__SEDORI_SELFTEST__.ok,true,'self test must pass');assert.strictEqual(E.money(1000,3000,10,230).profit,1470);assert(E.maxBuyFor(5000,10,230,3000,30)>=0);
let id=E.identity('K18 メンズ リング 18号');assert.strictEqual(id.category,'ring');assert(id.materials.includes('k18'));assert(id.sizes.includes('18'));assert(E.identity('K18 イミテーション リング').hardRisk.length>0);
const s=JSON.parse(JSON.stringify(E.DEFAULTS)),target={source:'mercari',title:'SV925 リング 18号',price:1000,url:'t'},peers=[{source:'mercari',title:'SV925 リング 18号 シンプル',price:3200,url:'1'},{source:'yahoo_fleamarket',title:'シルバー925 指輪 18号',price:3400,url:'2'},{source:'rakuma',title:'SV925 メンズ リング 18号',price:3600,url:'3'},{source:'yahoo_auction',title:'SV925 リング 18号',price:3300,url:'4'}];
const market=E.marketFor(target,[target,...peers],'SV925 リング 18号',s);assert.strictEqual(market.reliable,true,'4 comparable rows across sites should be reliable');assert(market.standard>0);const badMarket=E.marketFor(target,[target,peers[0]],'SV925 リング 18号',s);assert.strictEqual(badMarket.reliable,false);const hold=E.judge(target,badMarket,s);assert.strictEqual(hold.verdict,'HOLD');assert.strictEqual(hold.market.standard,0,'insufficient evidence must not have safe sale price');const loss=E.judge({...target,price:10000},market,s);assert.strictEqual(loss.verdict,'PASS');console.log('v13 tests passed');